//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_info
    {
        public string ad_id { get; set; }
        public string ad_title { get; set; }
        public string ad_img { get; set; }
        public string ad_type { get; set; }
        public Nullable<System.DateTime> ad_sdate { get; set; }
        public Nullable<System.DateTime> ad_edate { get; set; }
        public Nullable<System.DateTime> ad_date { get; set; }
    }
}
