//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_article
    {
        public string com_article_id { get; set; }
        public string com_article_title { get; set; }
        public string com_article_content { get; set; }
        public string com_article_class { get; set; }
        public string com_article_userid { get; set; }
        public Nullable<System.DateTime> com_article_date { get; set; }
    }
}
