//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_area
    {
        public int com_area_id { get; set; }
        public string com_area_name { get; set; }
        public string com_area_parentid { get; set; }
        public string com_area_shortname { get; set; }
        public string com_area_lng { get; set; }
        public string com_area_lat { get; set; }
        public string com_area_lev { get; set; }
        public string com_area_position { get; set; }
        public string com_area_sort { get; set; }
    }
}
