//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_img
    {
        public string com_img_id { get; set; }
        public string com_img_title { get; set; }
        public string com_img_alt { get; set; }
        public string com_img_src { get; set; }
        public string com_img_fk { get; set; }
        public string com_img_adduser { get; set; }
        public Nullable<System.DateTime> com_img_adddate { get; set; }
        public string com_img_edituser { get; set; }
        public Nullable<System.DateTime> com_img_editdate { get; set; }
    }
}
