//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_banner
    {
        public string com_banner_id { get; set; }
        public string com_banner_class { get; set; }
        public string com_banner_order { get; set; }
        public string com_banner_url { get; set; }
        public string com_banner_adduser { get; set; }
        public Nullable<System.DateTime> com_banner_adddate { get; set; }
        public string com_banner_edituser { get; set; }
        public Nullable<System.DateTime> com_banner_editdate { get; set; }
    }
}
