//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_brand
    {
        public string pro_brand_id { get; set; }
        public string pro_class_id { get; set; }
        public string pro_subclass_id { get; set; }
        public string pro_brand_name { get; set; }
        public string pro_brand_status { get; set; }
        public string pro_brand_adduser { get; set; }
        public Nullable<System.DateTime> pro_brand_adddate { get; set; }
        public string pro_brand_edituser { get; set; }
        public Nullable<System.DateTime> pro_brand_editdate { get; set; }
        public Nullable<int> pro_brand_order { get; set; }
    }
}
