//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_item
    {
        public string pro_item_id { get; set; }
        public string pro_class_id { get; set; }
        public string pro_subclass_id { get; set; }
        public string pro_brand_id { get; set; }
        public string pro_item_title { get; set; }
        public string pro_item_subtitle { get; set; }
        public string pro_item_covimg { get; set; }
        public string pro_item_arrimg { get; set; }
        public string pro_item_content { get; set; }
        public string pro_item_adduser { get; set; }
        public Nullable<System.DateTime> pro_item_adddate { get; set; }
        public string pro_item_edituser { get; set; }
        public Nullable<System.DateTime> pro_item_editdate { get; set; }
        public Nullable<int> pro_item_status { get; set; }
        public Nullable<int> pro_item_order { get; set; }
    }
}
