//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_classsub
    {
        public string pro_classsub_id { get; set; }
        public string pro_class_id { get; set; }
        public string pro_classsub_name { get; set; }
        public string pro_classsub_status { get; set; }
        public string pro_classsub_adduser { get; set; }
        public Nullable<System.DateTime> pro_classsub_adddate { get; set; }
        public string pro_classsub_edituser { get; set; }
        public Nullable<System.DateTime> pro_classsub_eidtdate { get; set; }
        public Nullable<int> pro_classsub_order { get; set; }
    }
}
