//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_spesub
    {
        public string pro_spesub_id { get; set; }
        public string pro_spe_id { get; set; }
        public string pro_spesub_name { get; set; }
        public string pro_spesub_value { get; set; }
        public string pro_spesub_status { get; set; }
        public string pro_spesub_adduser { get; set; }
        public Nullable<System.DateTime> pro_spesub_adddate { get; set; }
        public string pro_spesub_edituser { get; set; }
        public Nullable<System.DateTime> pro_spesub_editdate { get; set; }
        public Nullable<int> pro_spesub_order { get; set; }
    }
}
