//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_class
    {
        public string pro_class_id { get; set; }
        public Nullable<int> pro_class_order { get; set; }
        public string pro_class_name { get; set; }
        public string pro_parent { get; set; }
        public string pro_class_page { get; set; }
        public string pro_class_img { get; set; }
        public string pro_class_status { get; set; }
        public string pro_class_adduser { get; set; }
        public Nullable<System.DateTime> pro_class_adddate { get; set; }
        public string pro_class_edituser { get; set; }
        public Nullable<System.DateTime> pro_class_editdate { get; set; }
    }
}
