//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_sku
    {
        public string pro_sku_id { get; set; }
        public string pro_item_id { get; set; }
        public string pro_class_id { get; set; }
        public string pro_sku_code { get; set; }
        public string pro_sku_title { get; set; }
        public string pro_sku_covimg { get; set; }
        public string pro_sku_keywords { get; set; }
        public string pro_sku_description { get; set; }
        public string pro_sku_status { get; set; }
        public string pro_sku_arrspe { get; set; }
        public string pro_sku_adduser { get; set; }
        public Nullable<System.DateTime> pro_sku_adddate { get; set; }
        public string pro_sku_edituser { get; set; }
        public Nullable<System.DateTime> pro_sku_editdate { get; set; }
        public Nullable<int> pro_sku_order { get; set; }
    }
}
