//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_shipment
    {
        public string pro_shipment_id { get; set; }
        public string pro_express_id { get; set; }
        public string pro_shipment_starcity { get; set; }
        public string pro_shipment_province { get; set; }
        public string pro_shipment_city { get; set; }
        public string pro_shipment_county { get; set; }
        public string pro_shipment_price { get; set; }
        public string pro_shipment_adduser { get; set; }
        public Nullable<System.DateTime> pro_shipment_adddate { get; set; }
        public string pro_shipment_edituser { get; set; }
        public Nullable<System.DateTime> pro_shipment_editdate { get; set; }
    }
}
