//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_skuitem
    {
        public string pro_skuitem_id { get; set; }
        public string pro_sku_id { get; set; }
        public string pro_skuitem_code { get; set; }
        public string pro_item_id { get; set; }
        public string pro_class_id { get; set; }
        public string pro_subclass_id { get; set; }
        public string pro_brand_id { get; set; }
        public string pro_skuitem_name { get; set; }
        public string pro_skuitem_title { get; set; }
        public Nullable<decimal> pro_skuitem_price { get; set; }
        public Nullable<decimal> pro_skuitem_mprice { get; set; }
        public Nullable<decimal> pro_skuitem_pprice { get; set; }
        public Nullable<int> pro_skuitem_stock { get; set; }
        public string pro_skuitem_img { get; set; }
        public Nullable<int> pro_skuitem_status { get; set; }
        public string pro_skuitem_adduser { get; set; }
        public Nullable<System.DateTime> pro_skuitem_adddate { get; set; }
        public string pro_skuitem_edituser { get; set; }
        public Nullable<System.DateTime> pro_skuitem_editdate { get; set; }
        public Nullable<int> pro_skuitem_order { get; set; }
    }
}
