//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_comment
    {
        public string pro_comment_id { get; set; }
        public string pro_comment_star { get; set; }
        public string pro_comment_content { get; set; }
        public string pro_sku_code { get; set; }
        public string user_basic_id { get; set; }
        public Nullable<System.DateTime> pro_comment_date { get; set; }
    }
}
