//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_coupon
    {
        public string pro_coupon_id { get; set; }
        public string pro_coupon_name { get; set; }
        public Nullable<System.DateTime> pro_coupon_enddate { get; set; }
        public string pro_coupon_class { get; set; }
        public string pro_coupon_stastus { get; set; }
        public string pro_coupon_discount { get; set; }
        public string pro_coupon_fuliprice { get; set; }
        public string pro_coupon_derating { get; set; }
        public string pro_coupon_credit { get; set; }
        public string pro_coupon_num { get; set; }
        public Nullable<System.DateTime> pro_coupon_date { get; set; }
        public string pro_coupon_code { get; set; }
        public Nullable<System.DateTime> pro_coupon_stadate { get; set; }
    }
}
