//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_newsgoods
    {
        public int pro_newsgoods_id { get; set; }
        public string pro_sku_code { get; set; }
        public Nullable<int> pro_newsgoods_order { get; set; }
        public string pro_newsgoods_status { get; set; }
    }
}
