//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_choose
    {
        public string shop_choose_id { get; set; }
        public string shop_order_id { get; set; }
        public int shop_choose_code { get; set; }
        public Nullable<System.DateTime> shop_choose_date { get; set; }
        public string shop_choose_des { get; set; }
        public string shop_orderdetail_id { get; set; }
        public string shop_choose_status { get; set; }
        public string shop_choose_service { get; set; }
        public string shop_choose_isget { get; set; }
        public string user_basic_id { get; set; }
        public string user_address_id { get; set; }
        public string shop_express_name { get; set; }
        public string shop_express_code { get; set; }
        public string user_bank_username { get; set; }
        public string user_bank_name { get; set; }
        public string user_bank_code { get; set; }
        public string user_bank_address { get; set; }
    }
}
