//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_invoice
    {
        public int shop_invoice_id { get; set; }
        public string shop_invoice_class { get; set; }
        public string shop_invoice_username { get; set; }
        public string shop_invoice_usercode { get; set; }
        public string shop_invoice_company { get; set; }
        public string shop_order_id { get; set; }
    }
}
