//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_orderdetail
    {
        public string shop_orderdetail_id { get; set; }
        public string shop_order_id { get; set; }
        public string pro_skuitem_id { get; set; }
        public Nullable<int> shop_orderdetail_num { get; set; }
        public Nullable<decimal> shop_orderdetail_price { get; set; }
        public Nullable<decimal> shop_orderdetail_total { get; set; }
    }
}
