//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_order
    {
        public string shop_order_id { get; set; }
        public string shop_order_code { get; set; }
        public string user_address_id { get; set; }
        public string user_basic_id { get; set; }
        public string pro_coupon_id { get; set; }
        public string shop_pay_id { get; set; }
        public string shop_order_totalmoeny { get; set; }
        public string shop_shipping_id { get; set; }
        public string shop_order_remark { get; set; }
        public Nullable<System.DateTime> shop_order_buydate { get; set; }
        public Nullable<System.DateTime> shop_order_adddate { get; set; }
        public Nullable<System.DateTime> shop_order_editdate { get; set; }
        public string shop_order_status { get; set; }
        public string shop_order_waynum { get; set; }
        public string shop_order_shipmentnumber { get; set; }
    }
}
