//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_shipping
    {
        public string shop_shipping_id { get; set; }
        public string shop_shipping_name { get; set; }
        public string shop_shipping_adduser { get; set; }
        public Nullable<System.DateTime> shop_shipping_adddate { get; set; }
        public string shop_shipping_edituser { get; set; }
        public Nullable<System.DateTime> shop_shipping_editdate { get; set; }
    }
}
