//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_purview
    {
        public int sys_purview_id { get; set; }
        public string sys_purview_name { get; set; }
        public string sys_purview_page { get; set; }
        public string sys_purview_adduser { get; set; }
        public Nullable<System.DateTime> sys_purview_adddate { get; set; }
        public string sys_purview_edituser { get; set; }
        public Nullable<System.DateTime> sys_purview_editdate { get; set; }
    }
}
