//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_log
    {
        public string sys_log_id { get; set; }
        public string sys_log_name { get; set; }
        public string sys_log_ip { get; set; }
        public string sys_log_content { get; set; }
        public string sys_admin_id { get; set; }
        public Nullable<System.DateTime> sys_log_adddate { get; set; }
    }
}
