//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_detail
    {
        public string user_detail_id { get; set; }
        public string user_basic_id { get; set; }
        public string user_detail_firstname { get; set; }
        public string user_detail_lastname { get; set; }
        public string user_detail_birthday { get; set; }
        public string user_detail_photo { get; set; }
        public string user_detail_gender { get; set; }
        public string user_detail_tel { get; set; }
        public string user_detail_zipcode { get; set; }
        public string user_detail_phone { get; set; }
        public string user_detail_province { get; set; }
        public string user_detail_city { get; set; }
        public string user_detail_county { get; set; }
        public string user_detail_address { get; set; }
        public string user_detail_Fcard { get; set; }
        public string user_detail_Bcard { get; set; }
        public Nullable<System.DateTime> user_detail_adddate { get; set; }
        public Nullable<System.DateTime> user_detail_editdate { get; set; }
    }
}
