//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_address
    {
        public string user_address_id { get; set; }
        public string user_basic_id { get; set; }
        public string user_address_name { get; set; }
        public string user_address_tel { get; set; }
        public string user_address_province { get; set; }
        public string user_address_city { get; set; }
        public string user_address_county { get; set; }
        public string user_address_detail { get; set; }
        public Nullable<System.DateTime> user_address_adddate { get; set; }
        public Nullable<System.DateTime> user_address_editdate { get; set; }
        public string user_address_ZipCode { get; set; }
        public string user_address_tags { get; set; }
    }
}
